/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.handsonliferay.apress_service_builder.model.impl;

import com.handsonliferay.apress_service_builder.model.Emp;
import com.handsonliferay.apress_service_builder.model.EmpModel;
import com.handsonliferay.apress_service_builder.model.EmpSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Emp service. Represents a row in the &quot;apress_Emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmpModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpImpl}.
 * </p>
 *
 * @author Apoorva_Inthiyaz
 * @see EmpImpl
 * @generated
 */
@JSON(strict = true)
public class EmpModelImpl extends BaseModelImpl<Emp> implements EmpModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp model instance should use the <code>Emp</code> interface instead.
	 */
	public static final String TABLE_NAME = "apress_Emp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"EmpId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"projectId", Types.BIGINT}, {"projectName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"isCoding", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EmpId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("isCoding", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table apress_Emp (uuid_ VARCHAR(75) null,EmpId LONG not null primary key,groupId LONG,companyId LONG,projectId LONG,projectName VARCHAR(75) null,createDate DATE null,isCoding BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table apress_Emp";

	public static final String ORDER_BY_JPQL = " ORDER BY emp.projectId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY apress_Emp.projectId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISCODING_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROJECTID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Emp toModel(EmpSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Emp model = new EmpImpl();

		model.setUuid(soapModel.getUuid());
		model.setEmpId(soapModel.getEmpId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setProjectId(soapModel.getProjectId());
		model.setProjectName(soapModel.getProjectName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setIsCoding(soapModel.isIsCoding());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Emp> toModels(EmpSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Emp> models = new ArrayList<Emp>(soapModels.length);

		for (EmpSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public EmpModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _EmpId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _EmpId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Emp.class;
	}

	@Override
	public String getModelClassName() {
		return Emp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Emp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Emp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Emp, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Emp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Emp, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Emp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Emp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Emp, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Emp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Emp>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Emp.class.getClassLoader(), Emp.class, ModelWrapper.class);

		try {
			Constructor<Emp> constructor =
				(Constructor<Emp>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Emp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Emp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Emp, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Emp, Object>>();
		Map<String, BiConsumer<Emp, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Emp, ?>>();

		attributeGetterFunctions.put("uuid", Emp::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Emp, String>)Emp::setUuid);
		attributeGetterFunctions.put("EmpId", Emp::getEmpId);
		attributeSetterBiConsumers.put(
			"EmpId", (BiConsumer<Emp, Long>)Emp::setEmpId);
		attributeGetterFunctions.put("groupId", Emp::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Emp, Long>)Emp::setGroupId);
		attributeGetterFunctions.put("companyId", Emp::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Emp, Long>)Emp::setCompanyId);
		attributeGetterFunctions.put("projectId", Emp::getProjectId);
		attributeSetterBiConsumers.put(
			"projectId", (BiConsumer<Emp, Long>)Emp::setProjectId);
		attributeGetterFunctions.put("projectName", Emp::getProjectName);
		attributeSetterBiConsumers.put(
			"projectName", (BiConsumer<Emp, String>)Emp::setProjectName);
		attributeGetterFunctions.put("createDate", Emp::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Emp, Date>)Emp::setCreateDate);
		attributeGetterFunctions.put("isCoding", Emp::getIsCoding);
		attributeSetterBiConsumers.put(
			"isCoding", (BiConsumer<Emp, Boolean>)Emp::setIsCoding);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEmpId() {
		return _EmpId;
	}

	@Override
	public void setEmpId(long EmpId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EmpId = EmpId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectId = projectId;
	}

	@JSON
	@Override
	public String getProjectName() {
		if (_projectName == null) {
			return "";
		}
		else {
			return _projectName;
		}
	}

	@Override
	public void setProjectName(String projectName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_projectName = projectName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public boolean getIsCoding() {
		return _isCoding;
	}

	@JSON
	@Override
	public boolean isIsCoding() {
		return _isCoding;
	}

	@Override
	public void setIsCoding(boolean isCoding) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCoding = isCoding;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsCoding() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isCoding"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Emp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Emp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Emp> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpImpl empImpl = new EmpImpl();

		empImpl.setUuid(getUuid());
		empImpl.setEmpId(getEmpId());
		empImpl.setGroupId(getGroupId());
		empImpl.setCompanyId(getCompanyId());
		empImpl.setProjectId(getProjectId());
		empImpl.setProjectName(getProjectName());
		empImpl.setCreateDate(getCreateDate());
		empImpl.setIsCoding(isIsCoding());

		empImpl.resetOriginalValues();

		return empImpl;
	}

	@Override
	public Emp cloneWithOriginalValues() {
		EmpImpl empImpl = new EmpImpl();

		empImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		empImpl.setEmpId(this.<Long>getColumnOriginalValue("EmpId"));
		empImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		empImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		empImpl.setProjectId(this.<Long>getColumnOriginalValue("projectId"));
		empImpl.setProjectName(
			this.<String>getColumnOriginalValue("projectName"));
		empImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		empImpl.setIsCoding(this.<Boolean>getColumnOriginalValue("isCoding"));

		return empImpl;
	}

	@Override
	public int compareTo(Emp emp) {
		int value = 0;

		if (getProjectId() < emp.getProjectId()) {
			value = -1;
		}
		else if (getProjectId() > emp.getProjectId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Emp)) {
			return false;
		}

		Emp emp = (Emp)object;

		long primaryKey = emp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Emp> toCacheModel() {
		EmpCacheModel empCacheModel = new EmpCacheModel();

		empCacheModel.uuid = getUuid();

		String uuid = empCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			empCacheModel.uuid = null;
		}

		empCacheModel.EmpId = getEmpId();

		empCacheModel.groupId = getGroupId();

		empCacheModel.companyId = getCompanyId();

		empCacheModel.projectId = getProjectId();

		empCacheModel.projectName = getProjectName();

		String projectName = empCacheModel.projectName;

		if ((projectName != null) && (projectName.length() == 0)) {
			empCacheModel.projectName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			empCacheModel.createDate = createDate.getTime();
		}
		else {
			empCacheModel.createDate = Long.MIN_VALUE;
		}

		empCacheModel.isCoding = isIsCoding();

		return empCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Emp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Emp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Emp, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Emp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Emp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Emp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Emp, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Emp)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Emp>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _EmpId;
	private long _groupId;
	private long _companyId;
	private long _projectId;
	private String _projectName;
	private Date _createDate;
	private boolean _isCoding;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Emp, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Emp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("EmpId", _EmpId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("projectId", _projectId);
		_columnOriginalValues.put("projectName", _projectName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("isCoding", _isCoding);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("EmpId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("projectId", 16L);

		columnBitmasks.put("projectName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("isCoding", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Emp _escapedModel;

}