/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.handsonliferay.apress_service_builder.service.base;

import com.handsonliferay.apress_service_builder.model.ApressBook;
import com.handsonliferay.apress_service_builder.service.ApressBookLocalService;
import com.handsonliferay.apress_service_builder.service.ApressBookLocalServiceUtil;
import com.handsonliferay.apress_service_builder.service.persistence.ApressBookPersistence;
import com.handsonliferay.apress_service_builder.service.persistence.EmpPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the apress book local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.handsonliferay.apress_service_builder.service.impl.ApressBookLocalServiceImpl}.
 * </p>
 *
 * @author Apoorva_Inthiyaz
 * @see com.handsonliferay.apress_service_builder.service.impl.ApressBookLocalServiceImpl
 * @generated
 */
public abstract class ApressBookLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ApressBookLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ApressBookLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ApressBookLocalServiceUtil</code>.
	 */

	/**
	 * Adds the apress book to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApressBookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apressBook the apress book
	 * @return the apress book that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ApressBook addApressBook(ApressBook apressBook) {
		apressBook.setNew(true);

		return apressBookPersistence.update(apressBook);
	}

	/**
	 * Creates a new apress book with the primary key. Does not add the apress book to the database.
	 *
	 * @param bookId the primary key for the new apress book
	 * @return the new apress book
	 */
	@Override
	@Transactional(enabled = false)
	public ApressBook createApressBook(long bookId) {
		return apressBookPersistence.create(bookId);
	}

	/**
	 * Deletes the apress book with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApressBookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param bookId the primary key of the apress book
	 * @return the apress book that was removed
	 * @throws PortalException if a apress book with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ApressBook deleteApressBook(long bookId) throws PortalException {
		return apressBookPersistence.remove(bookId);
	}

	/**
	 * Deletes the apress book from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApressBookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apressBook the apress book
	 * @return the apress book that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ApressBook deleteApressBook(ApressBook apressBook) {
		return apressBookPersistence.remove(apressBook);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return apressBookPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ApressBook.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return apressBookPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.handsonliferay.apress_service_builder.model.impl.ApressBookModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return apressBookPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.handsonliferay.apress_service_builder.model.impl.ApressBookModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return apressBookPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return apressBookPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return apressBookPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ApressBook fetchApressBook(long bookId) {
		return apressBookPersistence.fetchByPrimaryKey(bookId);
	}

	/**
	 * Returns the apress book matching the UUID and group.
	 *
	 * @param uuid the apress book's UUID
	 * @param groupId the primary key of the group
	 * @return the matching apress book, or <code>null</code> if a matching apress book could not be found
	 */
	@Override
	public ApressBook fetchApressBookByUuidAndGroupId(
		String uuid, long groupId) {

		return apressBookPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the apress book with the primary key.
	 *
	 * @param bookId the primary key of the apress book
	 * @return the apress book
	 * @throws PortalException if a apress book with the primary key could not be found
	 */
	@Override
	public ApressBook getApressBook(long bookId) throws PortalException {
		return apressBookPersistence.findByPrimaryKey(bookId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(apressBookLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ApressBook.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("bookId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			apressBookLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ApressBook.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("bookId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(apressBookLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ApressBook.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("bookId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return apressBookPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return apressBookLocalService.deleteApressBook(
			(ApressBook)persistedModel);
	}

	@Override
	public BasePersistence<ApressBook> getBasePersistence() {
		return apressBookPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return apressBookPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the apress books matching the UUID and company.
	 *
	 * @param uuid the UUID of the apress books
	 * @param companyId the primary key of the company
	 * @return the matching apress books, or an empty list if no matches were found
	 */
	@Override
	public List<ApressBook> getApressBooksByUuidAndCompanyId(
		String uuid, long companyId) {

		return apressBookPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of apress books matching the UUID and company.
	 *
	 * @param uuid the UUID of the apress books
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of apress books
	 * @param end the upper bound of the range of apress books (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching apress books, or an empty list if no matches were found
	 */
	@Override
	public List<ApressBook> getApressBooksByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<ApressBook> orderByComparator) {

		return apressBookPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the apress book matching the UUID and group.
	 *
	 * @param uuid the apress book's UUID
	 * @param groupId the primary key of the group
	 * @return the matching apress book
	 * @throws PortalException if a matching apress book could not be found
	 */
	@Override
	public ApressBook getApressBookByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return apressBookPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the apress books.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.handsonliferay.apress_service_builder.model.impl.ApressBookModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of apress books
	 * @param end the upper bound of the range of apress books (not inclusive)
	 * @return the range of apress books
	 */
	@Override
	public List<ApressBook> getApressBooks(int start, int end) {
		return apressBookPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of apress books.
	 *
	 * @return the number of apress books
	 */
	@Override
	public int getApressBooksCount() {
		return apressBookPersistence.countAll();
	}

	/**
	 * Updates the apress book in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ApressBookLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param apressBook the apress book
	 * @return the apress book that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ApressBook updateApressBook(ApressBook apressBook) {
		return apressBookPersistence.update(apressBook);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ApressBookLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		apressBookLocalService = (ApressBookLocalService)aopProxy;

		_setLocalServiceUtilService(apressBookLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ApressBookLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ApressBook.class;
	}

	protected String getModelClassName() {
		return ApressBook.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = apressBookPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ApressBookLocalService apressBookLocalService) {

		try {
			Field field = ApressBookLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, apressBookLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected ApressBookLocalService apressBookLocalService;

	@Reference
	protected ApressBookPersistence apressBookPersistence;

	@Reference
	protected EmpPersistence empPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}