/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.handsonliferay.apress_service_builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the book service. Represents a row in the &quot;apress_book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.handsonliferay.apress_service_builder.model.impl.bookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.handsonliferay.apress_service_builder.model.impl.bookImpl</code>.
 * </p>
 *
 * @author Apoorva_Inthiyaz
 * @see book
 * @generated
 */
@ProviderType
public interface bookModel extends BaseModel<book>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book model instance should use the {@link book} interface instead.
	 */

	/**
	 * Returns the primary key of this book.
	 *
	 * @return the primary key of this book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book.
	 *
	 * @param primaryKey the primary key of this book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this book.
	 *
	 * @return the uuid of this book
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this book.
	 *
	 * @param uuid the uuid of this book
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the book ID of this book.
	 *
	 * @return the book ID of this book
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this book.
	 *
	 * @param bookId the book ID of this book
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the group ID of this book.
	 *
	 * @return the group ID of this book
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this book.
	 *
	 * @param groupId the group ID of this book
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this book.
	 *
	 * @return the company ID of this book
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this book.
	 *
	 * @param companyId the company ID of this book
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the chapter ID of this book.
	 *
	 * @return the chapter ID of this book
	 */
	public long getChapterId();

	/**
	 * Sets the chapter ID of this book.
	 *
	 * @param chapterId the chapter ID of this book
	 */
	public void setChapterId(long chapterId);

	/**
	 * Returns the chapter name of this book.
	 *
	 * @return the chapter name of this book
	 */
	@AutoEscape
	public String getChapterName();

	/**
	 * Sets the chapter name of this book.
	 *
	 * @param chapterName the chapter name of this book
	 */
	public void setChapterName(String chapterName);

	/**
	 * Returns the create date of this book.
	 *
	 * @return the create date of this book
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this book.
	 *
	 * @param createDate the create date of this book
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the is coding of this book.
	 *
	 * @return the is coding of this book
	 */
	public boolean getIsCoding();

	/**
	 * Returns <code>true</code> if this book is is coding.
	 *
	 * @return <code>true</code> if this book is is coding; <code>false</code> otherwise
	 */
	public boolean isIsCoding();

	/**
	 * Sets whether this book is is coding.
	 *
	 * @param isCoding the is coding of this book
	 */
	public void setIsCoding(boolean isCoding);

	@Override
	public book cloneWithOriginalValues();

}