/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.handsonliferay.apress_service_builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Emp service. Represents a row in the &quot;apress_Emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.handsonliferay.apress_service_builder.model.impl.EmpModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.handsonliferay.apress_service_builder.model.impl.EmpImpl</code>.
 * </p>
 *
 * @author Apoorva_Inthiyaz
 * @see Emp
 * @generated
 */
@ProviderType
public interface EmpModel extends BaseModel<Emp>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp model instance should use the {@link Emp} interface instead.
	 */

	/**
	 * Returns the primary key of this emp.
	 *
	 * @return the primary key of this emp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp.
	 *
	 * @param primaryKey the primary key of this emp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this emp.
	 *
	 * @return the uuid of this emp
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this emp.
	 *
	 * @param uuid the uuid of this emp
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the emp ID of this emp.
	 *
	 * @return the emp ID of this emp
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this emp.
	 *
	 * @param EmpId the emp ID of this emp
	 */
	public void setEmpId(long EmpId);

	/**
	 * Returns the group ID of this emp.
	 *
	 * @return the group ID of this emp
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this emp.
	 *
	 * @param groupId the group ID of this emp
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp.
	 *
	 * @return the company ID of this emp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp.
	 *
	 * @param companyId the company ID of this emp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the project ID of this emp.
	 *
	 * @return the project ID of this emp
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this emp.
	 *
	 * @param projectId the project ID of this emp
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the project name of this emp.
	 *
	 * @return the project name of this emp
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this emp.
	 *
	 * @param projectName the project name of this emp
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the create date of this emp.
	 *
	 * @return the create date of this emp
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp.
	 *
	 * @param createDate the create date of this emp
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the is coding of this emp.
	 *
	 * @return the is coding of this emp
	 */
	public boolean getIsCoding();

	/**
	 * Returns <code>true</code> if this emp is is coding.
	 *
	 * @return <code>true</code> if this emp is is coding; <code>false</code> otherwise
	 */
	public boolean isIsCoding();

	/**
	 * Sets whether this emp is is coding.
	 *
	 * @param isCoding the is coding of this emp
	 */
	public void setIsCoding(boolean isCoding);

	@Override
	public Emp cloneWithOriginalValues();

}